add doublehour
golang-module/carbon pull request #126
Opened 2022-04-20 09:08 UTC by dmzlingyin

2022-04-20 09:38 UTC, gouguoyin commented
子时、丑时这些概念是针对中国农历来说的，只有中国农历(包括日本、韩国等受中国历法影响的国家)才有，因此个人觉得应该放到 [calendar.lunar.go](https://github.com/golang-module/carbon/blob/master/calendar.lunar.go) 文件里，并且无需多语言支持。

2022-04-20 09:56 UTC, dmzlingyin commented
> 子时、丑时这些概念是针对中国农历来说的，只有中国农历(包括日本、韩国等受中国历法影响的国家)才有，因此个人觉得应该放到 [calendar.lunar.go](https://github.com/golang-module/carbon/blob/master/calendar.lunar.go) 文件里，并且无需多语言支持，其他语言也根本没有对应的翻译。

开始我也想了半天究竟要不要英文版，后来还是加上了。

2022-04-20 12:30 UTC, gouguoyin commented
我很早就有增加时辰、天干地支相关的方法，但是苦于没有权威的英文翻译，不知道如何命名方法名，我看你将时辰 翻译为`DoubleHour `，子时 翻译为 `FirstDoubleHour `，请教下这个翻译你是在哪里查到的

2022-04-21 01:23 UTC, gouguoyin requested changes
在谷歌上搜了下，`时辰`确实翻译为`DoubleHour`

2022-04-21 01:26 UTC, merged

2022-04-21 07:39 UTC, gouguoyin commented
感谢你贡献的代码，我在你的基础上做了些优化，并加到readme.md文档上